server {
    listen 80;
    server_name localhost;

    # Frontend
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # handover API call to Python Container
    location /api/telemetry {
        proxy_pass http://backend:8080/api/telemetry;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}