server {
    listen 80;
    server_name localhost;

    # Frontend v1
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Frontend v2
    location /v2 {
        root /usr/share/nginx/html;
        try_files /index2.html =404;
    }

    # API v1 proxy to Python Container (port 8080)
    location /api/telemetry {
        proxy_pass http://backend:8080/api/telemetry;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # API v2 proxy to Python Container (port 8081)
    location /api/v2/telemetry {
        proxy_pass http://backend2:8081/api/telemetry;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Frontend v3 - Dynamic Dashboard
    location /v3 {
        root /usr/share/nginx/html;
        try_files /index3.html =404;
    }

    # API v3 proxy to Python Container (port 8082)
    location /api/v3/ {
        proxy_pass http://backend3:8082/api/v3/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}